name: adaptive_navigation_scaffold
description: An adaptive navigation scaffold that places navigation items either in a sidebar or a bottom navbar depending on the viewport width.
version: 0.0.1
homepage:
repository: https://github.com/antoniusnaumann/adaptive-navigation-scaffold

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
